const PRICE_MONTH_UZS = 60000;
const PRICE_MONTH_OLD_UZS = 100000;
const FREE_TRIAL_MONTHS = 1;
const DISCOUNT_PERCENT = Math.round((1 - PRICE_MONTH_UZS / PRICE_MONTH_OLD_UZS) * 100);

module.exports = {
  SERVICE_NAME: 'qr.menu',
  PRICE_MONTH_UZS,
  PRICE_MONTH_OLD_UZS,
  FREE_TRIAL_MONTHS,
  DISCOUNT_PERCENT,
};
